// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJCklHMxviLJ92-PNRhhL9tDXcXg9937w',
    appId: '1:506210928647:web:a54b9af86a6795564002a2',
    messagingSenderId: '506210928647',
    projectId: 'subtrack-f36d0',
    authDomain: 'subtrack-f36d0.firebaseapp.com',
    storageBucket: 'subtrack-f36d0.firebasestorage.app',
    measurementId: 'G-WLVV6E3X74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjYBCb1loyuDiWgd6ae-fHXjJcgTOmk0Y',
    appId: '1:506210928647:android:01aba1836aed123e4002a2',
    messagingSenderId: '506210928647',
    projectId: 'subtrack-f36d0',
    storageBucket: 'subtrack-f36d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV-mrQddciSNlcUB-40wKQ9XEwgtsyGdE',
    appId: '1:506210928647:ios:41e6b2d49b183e884002a2',
    messagingSenderId: '506210928647',
    projectId: 'subtrack-f36d0',
    storageBucket: 'subtrack-f36d0.firebasestorage.app',
    iosBundleId: 'com.example.subtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV-mrQddciSNlcUB-40wKQ9XEwgtsyGdE',
    appId: '1:506210928647:ios:41e6b2d49b183e884002a2',
    messagingSenderId: '506210928647',
    projectId: 'subtrack-f36d0',
    storageBucket: 'subtrack-f36d0.firebasestorage.app',
    iosBundleId: 'com.example.subtrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJCklHMxviLJ92-PNRhhL9tDXcXg9937w',
    appId: '1:506210928647:web:e4ee1d74dc5beb694002a2',
    messagingSenderId: '506210928647',
    projectId: 'subtrack-f36d0',
    authDomain: 'subtrack-f36d0.firebaseapp.com',
    storageBucket: 'subtrack-f36d0.firebasestorage.app',
    measurementId: 'G-41LVKH0GC1',
  );
}
